import json
import re
import os

def translate_all():
    with open('packages/web/public/locales/en/translation.json', 'r', encoding='utf-8') as f:
        en = json.load(f)
        
    try:
        with open('packages/web/public/locales/id/translation.json', 'r', encoding='utf-8') as f:
            existing_id = json.load(f)
    except:
        existing_id = {}

    # Comprehensive dictionary for UI strings
    translations = dict(existing_id)

    # Core dictionary
    dictionary = {
        # Navigation & Headers
        "Language": "Bahasa",
        "Select language": "Pilih bahasa",
        "Search language...": "Cari bahasa...",
        "No language found.": "Bahasa tidak ditemukan.",
        "Theme": "Tema",
        "Light": "Terang",
        "Dark": "Gelap",
        "System": "Sistem",
        "Account Settings": "Pengaturan Akun",
        "Platform Settings": "Pengaturan Platform",
        "Project Settings": "Pengaturan Proyek",
        "General": "Umum",
        "Appearance": "Tampilan",
        "My Profile": "Profil Saya",
        "Sign out": "Keluar",
        "Sign in": "Masuk",
        "Log in": "Masuk",
        "Log out": "Keluar",
        "Sign up": "Daftar",
        "Register": "Daftar",
        "Forgot password?": "Lupa kata sandi?",
        "Reset password": "Atur ulang kata sandi",
        "Send reset instructions": "Kirim petunjuk reset",
        "Email": "Email",
        "Password": "Kata Sandi",
        "New Password": "Kata Sandi Baru",
        "Current Password": "Kata Sandi Saat Ini",
        "Confirm Password": "Konfirmasi Kata Sandi",
        "First Name": "Nama Depan",
        "Last Name": "Nama Belakang",
        "Full Name": "Nama Lengkap",
        
        # General Actions
        "Save": "Simpan",
        "Save changes": "Simpan perubahan",
        "Saved": "Tersimpan",
        "Saving...": "Menyimpan...",
        "Cancel": "Batal",
        "Delete": "Hapus",
        "Deleting...": "Menghapus...",
        "Deleted": "Dihapus",
        "Edit": "Ubah",
        "Editing": "Mengubah",
        "Create": "Buat",
        "Creating...": "Membuat...",
        "Created": "Dibuat",
        "New": "Baru",
        "Add": "Tambah",
        "Adding...": "Menambahkan...",
        "Added": "Ditambahkan",
        "Remove": "Hapus",
        "Removing...": "Menghapus...",
        "Removed": "Dihapus",
        "Update": "Perbarui",
        "Updating...": "Memperbarui...",
        "Updated": "Diperbarui",
        "Publish": "Publikasikan",
        "Publishing...": "Mempublikasikan...",
        "Published": "Dipublikasikan",
        "Unpublish": "Batal Publikasikan",
        "Duplicate": "Duplikat",
        "Duplicating...": "Menduplikasi...",
        "Rename": "Ganti Nama",
        "Search": "Cari",
        "Search...": "Cari...",
        "Filter": "Filter",
        "Filter by...": "Filter berdasarkan...",
        "Sort": "Urutkan",
        "Sort by": "Urutkan berdasarkan",
        "Refresh": "Segarkan",
        "Reload": "Muat Ulang",
        "Clear": "Bersihkan",
        "Clear all": "Bersihkan semua",
        "Close": "Tutup",
        "Open": "Buka",
        "Back": "Kembali",
        "Next": "Berikutnya",
        "Previous": "Sebelumnya",
        "Finish": "Selesai",
        "Done": "Selesai",
        "Submit": "Kirim",
        "Send": "Kirim",
        "Sending...": "Mengirim...",
        "Copy": "Salin",
        "Copied!": "Tersalin!",
        "Copied to clipboard": "Disalin ke papan klip",
        "Download": "Unduh",
        "Downloading...": "Mengunduh...",
        "Upload": "Unggah",
        "Uploading...": "Mengunggah...",
        "Export": "Ekspor",
        "Import": "Impor",
        "View": "Lihat",
        "View details": "Lihat rincian",
        "Details": "Rincian",
        "Status": "Status",
        "Action": "Aksi",
        "Actions": "Aksi",
        "Select": "Pilih",
        "Select all": "Pilih semua",
        "Deselect all": "Batal pilih semua",
        "Apply": "Terapkan",
        "Reset": "Atur Ulang",
        "Discard": "Buang",
        "Confirm": "Konfirmasi",
        "Continue": "Lanjutkan",
        "Manage": "Kelola",
        "Configure": "Konfigurasi",
        "Install": "Pasang",
        "Installing...": "Memasang...",
        "Uninstall": "Copot Pemasangan",
        "Enable": "Aktifkan",
        "Disable": "Nonaktifkan",
        "Enabled": "Diaktifkan",
        "Disabled": "Dinonaktifkan",
        "Active": "Aktif",
        "Inactive": "Tidak Aktif",
        "Default": "Bawaan",
        "Custom": "Kustom",
        "All": "Semua",
        "None": "Tidak Ada",
        "Unknown": "Tidak Diketahui",
        "Required": "Wajib",
        "Optional": "Opsional",
        "Yes": "Ya",
        "No": "Tidak",
        "OK": "OK",
        "Help": "Bantuan",
        "Documentation": "Dokumentasi",
        "Community": "Komunitas",
        "Support": "Dukungan",
        "Learn more": "Pelajari lebih lanjut",
        "Read more": "Baca selengkapnya",

        # Flow Builder & Engine
        "Flow": "Alur",
        "Flows": "Alur",
        "New flow": "Alur baru",
        "Create flow": "Buat alur",
        "Flow name": "Nama alur",
        "Flow description": "Deskripsi alur",
        "Flow status": "Status alur",
        "Flow runs": "Riwayat eksekusi alur",
        "Flow version": "Versi alur",
        "Trigger": "Pemicu",
        "Triggers": "Pemicu",
        "Select trigger": "Pilih pemicu",
        "Add trigger": "Tambah pemicu",
        "Step": "Langkah",
        "Steps": "Langkah-langkah",
        "Select step": "Pilih langkah",
        "Add step": "Tambah langkah",
        "Delete step": "Hapus langkah",
        "Duplicate step": "Duplikat langkah",
        "Test step": "Uji langkah",
        "Testing step...": "Menguji langkah...",
        "Generate sample data": "Buat data sampel",
        "Generating sample data...": "Membuat data sampel...",
        "No sample data found": "Data sampel tidak ditemukan",
        "Step output": "Output langkah",
        "Step input": "Input langkah",
        "Input": "Input",
        "Output": "Output",
        "Parameters": "Parameter",
        "Branch": "Percabangan",
        "Branching": "Percabangan",
        "Branch (If/Else)": "Percabangan (Jika/Maka)",
        "Condition": "Kondisi",
        "Conditions": "Kondisi",
        "True branch": "Cabang benar",
        "False branch": "Cabang salah",
        "Loop": "Perulangan",
        "Loop over items": "Ulangi setiap item",
        "Items to loop over": "Item yang akan diulang",
        "Router": "Router",
        "Router rules": "Aturan router",
        "Piece": "Komponen",
        "Pieces": "Komponen",
        "Select a piece": "Pilih komponen",
        "Community pieces": "Komponen komunitas",
        "Custom pieces": "Komponen kustom",
        "Official pieces": "Komponen resmi",
        "Piece version": "Versi komponen",
        "Connections": "Koneksi",
        "Connection": "Koneksi",
        "New Connection": "Koneksi Baru",
        "Add connection": "Tambah koneksi",
        "Reconnect": "Hubungkan Ulang",
        "Test connection": "Uji koneksi",
        "Connected": "Terhubung",
        "Disconnected": "Terputus",
        "Connecting...": "Menghubungkan...",
        "Webhook": "Webhook",
        "Webhook URL": "URL Webhook",
        "Copy webhook URL": "Salin URL Webhook",
        "Polling": "Polling",
        "Runs": "Riwayat Eksekusi",
        "Run": "Jalankan",
        "Run flow": "Jalankan alur",
        "Running flow...": "Menjalankan alur...",
        "Run ID": "ID Eksekusi",
        "Duration": "Durasi",
        "Started at": "Dimulai pada",
        "Finished at": "Selesai pada",
        "Execution time": "Waktu eksekusi",
        "Succeeded": "Berhasil",
        "Failed": "Gagal",
        "Running": "Sedang Berjalan",
        "Paused": "Dijeda",
        "Skipped": "Dilewati",
        "Waiting": "Menunggu",
        "Queued": "Dalam Antrean",
        "Internal error": "Kesalahan internal",
        "Retry": "Coba Lagi",
        "Retry run": "Coba lagi eksekusi",
        "Retrying...": "Mencoba lagi...",
        "Folder": "Folder",
        "Folders": "Folder",
        "New folder": "Folder baru",
        "Move to folder": "Pindahkan ke folder",
        "Uncategorized": "Tanpa Kategori",
        "Draft": "Draf",
        "Live": "Aktif",
        "Draft version": "Versi draf",
        "Published version": "Versi terpublikasi",
        "Version history": "Riwayat versi",
        "Revert to this version": "Kembalikan ke versi ini",
        "Publish flow": "Publikasikan alur",
        "Publishing flow...": "Mempublikasikan alur...",
        "Flow published successfully": "Alur berhasil dipublikasikan",
        
        # Agents & AI
        "Agent": "Agen",
        "Agents": "Agen",
        "New agent": "Agen baru",
        "Create agent": "Buat agen",
        "Agent name": "Nama agen",
        "Agent description": "Deskripsi agen",
        "Agent instructions": "Instruksi agen",
        "Instructions": "Instruksi",
        "Describe what this agent should do": "Jelaskan apa yang harus dilakukan agen ini",
        "Model": "Model",
        "Select model": "Pilih model",
        "AI Provider": "Penyedia AI",
        "Tools": "Alat",
        "Add tool": "Tambah alat",
        "Available tools": "Alat yang tersedia",
        "MCP Tools": "Alat MCP",
        "MCP Servers": "Server MCP",
        "Add MCP Server": "Tambah Server MCP",
        "Knowledge": "Pengetahuan",
        "Knowledge base": "Basis pengetahuan",
        "Add knowledge": "Tambah pengetahuan",
        "Memory": "Memori",
        "Chat with AI": "Obrolan dengan AI",
        "Chat with Agent": "Obrolan dengan Agen",
        "Chat": "Obrolan",
        "New chat": "Obrolan baru",
        "Start new chat": "Mulai obrolan baru",
        "Ask anything...": "Tanyakan apa saja...",
        "Type a message...": "Ketik pesan...",
        "Thinking...": "Sedang berpikir...",
        "Copilot": "Kopilot",
        "Generate with AI": "Hasilkan dengan AI",
        "Ask AI to generate flow": "Minta AI untuk membuat alur",
        "Ask AI to write code": "Minta AI untuk menulis kode",
        "Describe the flow you want to build": "Deskripsikan alur yang ingin Anda buat",
        "Runs the published version. Editing it changes every flow using it.": "Menjalankan versi yang dipublikasikan. Mengeditnya akan mengubah setiap alur yang menggunakannya.",
        "Copies the tools and model. Instructions stay with the agent.": "Menyalin alat dan model. Instruksi tetap berada pada agen.",
        "MCP tools were left behind. Their credentials stay with the agent, so add them again here.": "Alat MCP ditinggalkan. Kredensialnya tetap berada pada agen, jadi tambahkan kembali di sini.",
        "Runs the published version, shared with every flow using it.": "Menjalankan versi yang dipublikasikan, dibagikan ke setiap alur yang menggunakannya.",
        "Detaching copies the tools and model here, not the instructions.": "Melepaskan salinan alat dan model ke sini, bukan instruksinya.",
        "This step runs the published agent. Editing the agent changes every flow that uses it.": "Langkah ini menjalankan agen yang dipublikasikan. Mengedit agen akan mengubah setiap alur yang menggunakannya.",
        "Detaching copies its tools and model into this step. Its instructions stay with the agent.": "Melepaskan menyalin alat dan model ke langkah ini. Instruksinya tetap berada pada agen.",
        "An MCP tool keeps its credentials on the agent, so this step could not take them. Add those tools again here.": "Alat MCP menyimpan kredensial pada agen, sehingga langkah ini tidak dapat membawanya. Tambahkan alat tersebut kembali di sini.",
        "Instructions, tools and model come from the agent. Editing the agent changes what this step runs.": "Instruksi, alat, dan model berasal dari agen. Mengedit agen akan mengubah apa yang dijalankan langkah ini.",
        "This agent has never been published, and a flow runs the published version.": "Agen ini belum pernah dipublikasikan, dan alur menjalankan versi yang dipublikasikan.",
        "This agent is not in this project, so the step cannot run.": "Agen ini tidak ada di proyek ini, sehingga langkah tidak dapat dijalankan.",
        "Fires when an agent runs a configured action that is not a read.": "Dijalankan ketika agen menjalankan aksi terkonfigurasi yang bukan berupa pembacaan.",
        "An agent is an assistant with instructions and tools. Describe the job and I'll write both.": "Agen adalah asisten dengan instruksi dan alat. Deskripsikan tugasnya dan saya akan menulis keduanya.",
        "Ask your platform admin to connect an AI provider.": "Minta admin platform Anda untuk menghubungkan penyedia AI.",
        "Ask your platform admin to turn on a provider for chat.": "Minta admin platform Anda untuk mengaktifkan penyedia untuk obrolan.",
        
        # Tables & Records
        "Tables": "Tabel",
        "Table": "Tabel",
        "New table": "Tabel baru",
        "Create table": "Buat tabel",
        "Table name": "Nama tabel",
        "Table description": "Deskripsi tabel",
        "Row": "Baris",
        "Rows": "Baris",
        "Add row": "Tambah baris",
        "Delete row": "Hapus baris",
        "Column": "Kolom",
        "Columns": "Kolom",
        "Add column": "Tambah kolom",
        "Delete column": "Hapus kolom",
        "Column name": "Nama kolom",
        "Column type": "Tipe kolom",
        "Text": "Teks",
        "Number": "Angka",
        "Boolean": "Boolean",
        "Date": "Tanggal",
        "JSON": "JSON",
        "File": "File",
        "Record": "Data",
        "Records": "Data",
        "View records": "Lihat data",

        # Team & Project Settings
        "Team": "Tim",
        "Members": "Anggota",
        "Invite member": "Undang anggota",
        "Invite members": "Undang anggota",
        "Send invitation": "Kirim undangan",
        "Pending invitations": "Undangan tertunda",
        "Role": "Peran",
        "Admin": "Admin",
        "Editor": "Editor",
        "Viewer": "Peninjau",
        "Operator": "Operator",
        "Owner": "Pemilik",
        "Project": "Proyek",
        "Projects": "Proyek",
        "New project": "Proyek baru",
        "Create project": "Buat proyek",
        "Switch project": "Ganti proyek",
        "Project name": "Nama proyek",
        "API Keys": "Kunci API",
        "New API Key": "Kunci API Baru",
        "Create API Key": "Buat Kunci API",
        "API Key name": "Nama Kunci API",
        "Signing Keys": "Kunci Penandatanganan",
        "Audit Logs": "Log Audit",
        "Custom Domains": "Domain Kustom",
        "Add custom domain": "Tambah domain kustom",
        "Branding": "Branding",
        "Logo": "Logo",
        "Favicon": "Favicon",
        "App title": "Judul aplikasi",
        "Git Sync": "Sinkronisasi Git",
        "Connect Git repository": "Hubungkan repositori Git",
        "Repository URL": "URL Repositori",
        "Branch": "Branch",
        "Push to Git": "Kirim ke Git",
        "Pull from Git": "Tarik dari Git",
        "Alerts": "Peringatan",
        "Email alerts": "Peringatan email",

        # Billing & Plans
        "Billing": "Tagihan & Langganan",
        "Plans": "Paket",
        "Plan": "Paket",
        "Current plan": "Paket saat ini",
        "Change plan": "Ubah paket",
        "Upgrade": "Tingkatkan Paket",
        "Upgrade plan": "Tingkatkan paket",
        "Manage subscription": "Kelola langganan",
        "Cancel subscription": "Batalkan langganan",
        "Resume subscription": "Lanjutkan langganan",
        "Payment method": "Metode pembayaran",
        "Update payment method": "Perbarui metode pembayaran",
        "Invoices": "Faktur",
        "Invoice history": "Riwayat faktur",
        "Tasks": "Tugas",
        "Tasks used": "Tugas terpakai",
        "Credits": "Kredit",
        "Credits balance": "Saldo kredit",
        "Credits used": "Kredit terpakai",
        "Auto top-up": "Isi ulang otomatis",
        "Usage": "Penggunaan",
        "Included credits": "Kredit termasuk",
        "Additional credits": "Kredit tambahan",
        "Included seats": "Kursi pengguna termasuk",
        "Additional seats": "Kursi pengguna tambahan",
        "Monthly": "Bulanan",
        "Yearly": "Tahunan",
        "Billed monthly": "Ditagih bulanan",
        "Billed yearly": "Ditagih tahunan",
        "Save 20%": "Hemat 20%",
        "Activepieces": "Anticeil",
        "activepieces": "anticeil",
    }

    # Sentence translation patterns and rules
    patterns = [
        (r'\bActivepieces\b', 'Anticeil'),
        (r'\bactivepieces\b', 'anticeil'),
        (r'\bAre you sure you want to delete\b', 'Apakah Anda yakin ingin menghapus'),
        (r'\bAre you sure you want to\b', 'Apakah Anda yakin ingin'),
        (r'\bThis action cannot be undone\b', 'Tindakan ini tidak dapat dibatalkan'),
        (r'\bPlease try again later\b', 'Silakan coba lagi nanti'),
        (r'\bFailed to fetch\b', 'Gagal memuat'),
        (r'\bFailed to load\b', 'Gagal memuat'),
        (r'\bFailed to save\b', 'Gagal menyimpan'),
        (r'\bFailed to delete\b', 'Gagal menghapus'),
        (r'\bFailed to create\b', 'Gagal membuat'),
        (r'\bFailed to update\b', 'Gagal memperbarui'),
        (r'\bFailed to publish\b', 'Gagal mempublikasikan'),
        (r'\bSuccessfully saved\b', 'Berhasil disimpan'),
        (r'\bSuccessfully deleted\b', 'Berhasil dihapus'),
        (r'\bSuccessfully created\b', 'Berhasil dibuat'),
        (r'\bSuccessfully updated\b', 'Berhasil diperbarui'),
        (r'\bSuccessfully published\b', 'Berhasil dipublikasikan'),
        (r'\bhas been deleted\b', 'telah dihapus'),
        (r'\bhas been created\b', 'telah dibuat'),
        (r'\bhas been updated\b', 'telah diperbarui'),
        (r'\bhas been saved\b', 'telah disimpan'),
        (r'\bhas been published\b', 'telah dipublikasikan'),
        (r'\bmust be at least (\d+) characters\b', r'harus minimal \1 karakter'),
        (r'\bmust be at most (\d+) characters\b', r'harus maksimal \1 karakter'),
        (r'\bis required\b', 'wajib diisi'),
        (r'\bis invalid\b', 'tidak valid'),
        (r'\bInvalid email address\b', 'Alamat email tidak valid'),
        (r'\bInvalid URL\b', 'URL tidak valid'),
        (r'\bPasswords do not match\b', 'Kata sandi tidak cocok'),
        (r'\bClick here to\b', 'Klik di sini untuk'),
        (r'\bLearn more about\b', 'Pelajari lebih lanjut tentang'),
    ]

    def auto_translate_string(s):
        if not s or not isinstance(s, str):
            return s
            
        # Check direct dictionary
        if s in dictionary:
            return dictionary[s]
            
        # ICU format check: {count, plural, one {# item} other {# items}}
        plural_match = re.match(r'^\{(\w+),\s*plural,\s*one\s*\{([^}]+)\}\s*other\s*\{([^}]+)\}\}$', s)
        if plural_match:
            var_name = plural_match.group(1)
            one_val = plural_match.group(2)
            other_val = plural_match.group(3)
            # In Indonesian, plurals don't have separate singular/plural noun forms
            trans_val = auto_translate_string(one_val)
            return f"{{{var_name}, plural, other {{{trans_val}}}}}"

        # Clean Activepieces references
        res = s
        for pat, repl in patterns:
            res = re.sub(pat, repl, res, flags=re.IGNORECASE)
            
        # Common word replacements for sentences
        word_map = {
            "Select a ": "Pilih ",
            "Choose a ": "Pilih ",
            "Enter a ": "Masukkan ",
            "Enter your ": "Masukkan ",
            "Please enter ": "Silakan masukkan ",
            "There are no ": "Tidak ada ",
            "No ": "Tidak ada ",
            " flows found": " alur ditemukan",
            " steps found": " langkah ditemukan",
            " pieces found": " komponen ditemukan",
            " runs found": " eksekusi ditemukan",
            " connections found": " koneksi ditemukan",
            " members found": " anggota ditemukan",
            " projects found": " proyek ditemukan",
            " tables found": " tabel ditemukan",
            " records found": " data ditemukan",
        }
        for k, v in word_map.items():
            if k in res:
                res = res.replace(k, v)

        # If unchanged but simple phrase
        if res == s and s in dictionary:
            return dictionary[s]
            
        return res

    # Build final dictionary for all keys in en.json
    count_translated = 0
    for key, en_val in en.items():
        # If we have an existing translation and it's not identical to EN key (unless EN key is universal like 'OK', 'JSON')
        if key in existing_id and existing_id[key] != key:
            # Keep existing translated string, replace Activepieces with Anticeil
            val = existing_id[key]
            val = val.replace("Activepieces", "Anticeil").replace("activepieces", "anticeil")
            translations[key] = val
        else:
            translated = auto_translate_string(en_val)
            translations[key] = translated
            count_translated += 1

    print(f"Total keys processed: {len(translations)}")
    print(f"Newly translated / updated: {count_translated}")
    
    with open('packages/web/public/locales/id/translation.json', 'w', encoding='utf-8') as f:
        json.dump(translations, f, ensure_ascii=False, indent=2)

if __name__ == '__main__':
    translate_all()
